baseurl = "/"
languageCode = "en-US"
title = "Patrick Martin Music"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "avatar.jpg"
  author = "Patrick Martin"
  description = "Patrick Martin is a freelance vocalist and guitarist based in Chicago, IL."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "username"
  Email         = "email@example.com"
  Twitter       = "username"
  LinkedIn      = "username"
  Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "About"
  weight = 100
  identifier = "blog"
  url = "/"
[[menu.main]]
  name = "Listen"
  identifier = "projects"
  weight = 200
  url = "/"
[[menu.main]]
  name = "Kid's Music"
  identifier = "resume"
  weight = 300
  url = "/"
[[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 400
  url = "/"
